---
hxr_custom_group:
  name: galaxy
hxr_custom_user:
  name: galaxy
  comment: "Galaxy Service-Acct"
  shell: /bin/bash

usegalaxy_eu_autofs_mounts:
 - data

certbot_auth_method: --webroot
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - nginx
  - proftpd
certbot_post_renewal: |
  systemctl restart nginx || true
  systemctl restart proftpd || true

# NGINX
nginx_enable_default_server: false
nginx_ssl_servers:
  - ftp
nginx_conf_http:
  client_max_body_size: 1g

# Nginx Letsencrypt bindings
nginx_ssl_role: usegalaxy-eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/user/privkey-nginx.pem


# ProFTPd
proftpd_allow_download:
  - hxr@informatik.uni-freiburg.de
  - bot@usegalaxy.eu
galaxy_ftp_upload_dir: /data/0/incoming/
galaxy_user:
  name: galaxy
proftpd_display_connect: |
    UseGalaxy.eu FTP
proftpd_galaxy_auth: yes
proftpd_options:
  - User: galaxy
  - Group: galaxy
galaxy_db_schema: galaxy
proftpd_tls_cipher_suite: AES128+EECDH:AES128+EDH
proftpd_tls_protocol: TLSv1.2
proftpd_conf_ssl_certificate: /etc/ssl/certs/cert.pem
proftpd_conf_ssl_certificate_key: /etc/ssl/user/privkey-proftpd.pem
proftpd_conf_ssl_ca_certificate: /etc/ssl/certs/fullchain.pem
proftpd_virtualhosts:
  - id: galaxy
    address: "{{ hostname }}"
    options:
      - ServerAdmin: admin@usegalaxy.eu
      - ServerName: UFR Galaxy FTP
      - TransferLog: "/var/log/proftpd/xfer/{{ hostname }}"
      - MaxLoginAttempts: 3
      - RequireValidShell: no
      - AllowOverwrite: yes
