# GAPARS Deployment
gapars_dir: /opt/gapars
gapars_user: gapars
gapars_group: gapars
gapars_version: master
gapars_create_group: true
gapars_create_user: true
gapars_force_checkout: true

gapars_listen_url: "127.0.0.1:5001"

gapars_nginx_config: |
    location /gapars-experiment/ {
        proxy_pass    http://{{ gapars_listen_url }}/;
        proxy_set_header           Host $host;
    }

    location /gapars-experiment/img/ {
        alias {{ gapars_dir }}/code/img/;
    }
