---
hxr_sentry_repodir: /tmp/sentry-code
hxr_sentry_datadir: /tmp/sentry-data
hxr_sentry_user: centos
hxr_sentry_group: centos
hxr_sentry_version: cd13427aa9a231b2b27c9fd14017d183cca52c1e

hxr_sentry_mail: {}
    #backend: 'smtp'
    #host: 'localhost'
    #port: 25
    #username: ''
    #password: ''
    #use-tls: 'false'
    #from: 'root@localhost'
    #enable-replies: 'false'
    #reply-hostname: ''
    #mailgun-api-key: ''


#hxr_sentry_secret_key: 'asdf'
#hxr_sentry_github_app_id: 'asdf'
#hxr_sentry_github_api_secret: 'asdfasdf'
