---
- hosts: hicbrowser
  become: true
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - hxr.admin-agents
    - influxdata.chrony
    - geerlingguy.repo-epel
    - hxr.monitor-email
    - linuxhq.yum_cron
    - hxr.autofs
    # BEGIN custom
    - geerlingguy.pip
    - geerlingguy.docker
    # END custom
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
