---
- name: "Deploy exporter script"
  copy:
    content: |
        #!/bin/bash
        . {{ galaxy_root }}/.bashrc
        . {{ galaxy_venv_dir }}/bin/activate
        python {{ galaxy_server_dir }}/scripts/grt/export.py -g {{ galaxy_config_dir }}/grt.yml -r {{ galaxy_mutable_data_dir }}/reports/ -b 10000 -c {{ galaxy_config_dir }}/galaxy.ini
    dest: /usr/bin/galaxy-grt-export
    owner: root
    group: root
    mode: 0755

- name: Add to cron
  cron:
    name: "GRT Export"
    minute: 0
    hour: 0
    weekday: 2
    job: /usr/bin/galaxy-grt-export
    user: "{{ galaxy_user.name }}"
