---
- name: docker
  hosts: docker
  become: true
  vars:
    hostname: docker.galaxyproject.eu
  vars_files:
    - "secret_group_vars/all.yml"
  roles:
    - hostname
    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - hxr.admin-agents
    - influxdata.chrony
    - hxr.monitor-email
    - linuxhq.yum_cron
    - galaxyproject.nginx
    # Custom
    - hxr.docker-ssl
    - geerlingguy.docker
    # End Custom
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
    - dev-sec.ssh-hardening
