- src: dev-sec.os-hardening
  version: 4.2.0
- src: geerlingguy.nfs
  version: 1.5.0
- src: devops.tomcat7
  version: 1.0.0
- src: dj-wasabi.telegraf
  version: 0.10.0
- src: https://github.com/galaxyproject/ansible-galaxy
  name: galaxyproject.galaxy
  version: 0.9.6
- src: galaxyproject.cvmfs
  version: 0.2.1
- src: galaxyproject.proftpd
  version: 0.2.4
- src: galaxyproject.nginx
  version: 0.6.4
- src: galaxyproject.postgresql
  version: 1.0.1
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.gitlab
  version: 2.5.1
- src: geerlingguy.java
  version: 1.9.5
- src: geerlingguy.jenkins
  version: 3.2.0
- src: geerlingguy.nodejs
  version: 4.2.2
- src: geerlingguy.pip
  version: 1.0.0
- src: geerlingguy.repo-epel
  version: 1.2.2
- src: https://github.com/usegalaxy-eu/ansible-chrony
  name: influxdata.chrony
  version: "0.1"
- src: jasonroyle.rabbitmq
  version: 0.0.4
- src: linuxhq.yum_cron
  version: master
- src: usegalaxy_eu.influxdb
  version: v6.0.6
- src: https://github.com/usegalaxy-eu/ansible-gxadmin
  name: usegalaxy-eu.gxadmin
  version: 0.0.6
- src: https://github.com/usegalaxy-eu/ansible-certbot
  name: usegalaxy-eu.certbot
  version: master
- src: https://github.com/usegalaxy-eu/ansible-galaxy-systemd
  name: usegalaxy-eu.galaxy-systemd
  version: 0.1.4
- src: https://github.com/usegalaxy-eu/ansible-dynmotd
  name: usegalaxy-eu.dynmotd
  version: master
- src: cloudalchemy.grafana
  version: 0.14.2
- src: geerlingguy.docker
  version: 2.5.2
- src: https://github.com/usegalaxy-eu/ansible-tiaas2
  name: usegalaxy_eu.tiaas2
  version: 0.0.6

