---
- cron:
    name: Docker cleanup
    job: ". {{ galaxy_root }}/.bashrc && docker system prune -f > /dev/null"
    minute: 30
    hour: 2

- cron:
    name: Cleanup held jobs
    job: condor_q -hold -autoformat ClusterId EnteredCurrentStatus CurrentTime | awk '(($3-$2) > (60*60)){print $1}' | xargs --no-run-if-empty condor_rm
    minute: 15
