galaxy_interactive_environment_dir: "{{ galaxy_config_dir }}/plugins/interactive_environments"
galaxy_interactive_environments:
- name: jupyter
  config: |
    [main]
    password_auth = True
    ssl = True
    [docker]
    docker_hostname = docker.galaxyproject.eu
    docker_connect_port = 80
    use_volumes = False
  allowed_images:
  - image: 'quay.io/bgruening/docker-jupyter-notebook:17.09'
    description: >
        The Jupyter notebook is the next iteration of IPython, allowing
        analysis in many different languages. This image features the Python,
        R, Julia, Haskell, Bash kernels and many scientific analysis stacks for
        each.

- name: rstudio
  config: |
    [main]
    password_auth = True
    ssl = True
    [docker]
    docker_hostname = docker.galaxyproject.eu
    docker_connect_port = 80
    use_volumes = False
  allowed_images:
  - image: 'quay.io/erasche/docker-rstudio-notebook:19.05'
    description: >
        This familiar R analysis software suite will let you explore your
        datasets in depth. Comes with ggplot2, RODBC, maps, shinyapps, knitr,
        LaTeX, bioconductor, cummeRbund, and many more pre-installed packages.
