---
- name: "Deploy file"
  copy:
    content: |
        google-site-verification: {{ google_site_verification_id }}
    dest: /usr/share/nginx/html/{{ google_site_verification_id }}
    owner: nginx
    group: nginx
    mode: 0755

- name: Export some NGINX configuration
  set_fact:
    google_site_verification: |
        location /{{ google_site_verification_id }} {
            root /usr/share/nginx/html;
        }
