---
- name: Ensure curl is installed
  package:
    name: curl
    state: present

- name: Deploy squid data parser
  copy:
    src: "parse_squid.py"
    dest: "/usr/bin/parse_squid.py"
    owner: root
    group: root
    mode: 0755
  notify: 'Restart Telegraf'

- name: Deploy squid data wrapper
  copy:
    src: "parse_squid.sh"
    dest: "/usr/bin/parse_squid"
    owner: root
    group: root
    mode: 0755
  notify: 'Restart Telegraf'

- set_fact:
    check_squid_telegraf:
      check_squid_telegraf:
        plugin: "exec"
        config:
          - commands = ["/usr/bin/parse_squid"]
          - timeout = "10s"
          - data_format = "influx"
          - interval = "5m"

- set_fact:
    telegraf_plugins_extra: "{{ telegraf_plugins_extra | combine(check_squid_telegraf) }}"
