---
# tasks file for ansible-role-tomcat7

# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Setup/install tasks.
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Configure.
- include: configure.yml
