---
- name: Check for bashrc
  stat:
    path: "~/.bashrc"
  register: bashrc_stat_out

- name: Copy default bashrc when not existing
  copy:
    src: /etc/skel/.bashrc
    dest: "~/.bashrc"
    remote_src: yes
    mode: 0750
  when: not bashrc_stat_out.stat.exists
