---
- name: add bintray rabbitmq-server repo
  yum_repository:
    name: bintray-rabbitmq-rpm
    description: 'asdf'
    baseurl: "https://dl.bintray.com/rabbitmq/rpm/rabbitmq-server/v3.7.x/el/$releasever/"
    gpgcheck: false
    repo_gpgcheck: false
    enabled: true

- name: install erlang
  yum:
    name: https://github.com/rabbitmq/erlang-rpm/releases/download/v21.3.8.3/erlang-21.3.8.3-1.el7.x86_64.rpm

- name: install rabbitmq
  yum:
    name: rabbitmq-server
