---
- stat: path=/etc/ssh/ssh_host_rsa_key-cert.pub
  register: st

- name: Copy server key into VM temporarily
  copy:
    src: server_ca
    dest: /tmp/server_ca
    owner: root
    group: root
    mode: 0600
  when: not st.stat.exists

- name: Sign Keys
  command: ssh-keygen -s /tmp/server_ca -I key_for_test1 -h -V +520w /etc/ssh/ssh_host_{{ item }}_key.pub
  with_items:
    - rsa
    - ecdsa
    - ed25519
  when: not st.stat.exists

# Requires dev-sec.ssh-hardening + patches
- set_fact:
    ssh_host_key_cert_files:
      - /etc/ssh/ssh_host_rsa_key-cert.pub
      - /etc/ssh/ssh_host_ecdsa_key-cert.pub
      - /etc/ssh/ssh_host_ed25519_key-cert.pub
  notify: "restart sshd"

- name: Ensure server key is gone
  file:
    path: /tmp/server_ca
    state: absent
  when: not st.stat.exists

- name: "Helper"
  debug:
    msg: "Please add the following to your known_hosts file: @cert-authority <ip-range|*.domain> {{ lookup('file', 'server_ca.pub')  }}"
