- name: "Copy procstat setup"
  template:
    src: "telegraf-procstat.conf.j2"
    dest: "/etc/telegraf/telegraf.d/galaxy_procstat.conf"
    owner: telegraf
    group: telegraf
    mode: 0640
  notify: "Restart Telegraf"
