---
- name: "Deploy fixer upper script"
  copy:
    content: |
        #!/bin/bash
        . {{ galaxy_root }}/.bashrc
        for user in $(gxadmin mutate oidc-role-find-affected); do
            gxadmin mutate oidc-role-fix $user;
        done;
    dest: /usr/bin/galaxy-fix-oidc
    owner: root
    group: root
    mode: 0755

- name: Add to cron
  cron:
    name: "Fix OIDC for galaxyproject/galaxy#8244"
    minute: "*/5"
    user: "{{ galaxy_user.name }}"
    job: /usr/bin/galaxy-fix-oidc
